import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Welcome to <span className={styles.pinkSpan}>Welinder.lol</span>
            <br />
            <br />
          </h1>
          <h2 className={styles.subtitle}>
            <span className={styles.pinkSpan}>Welinder.lol</span> is a
            <span className={styles.pinkSpan}> Tinder</span> clone for
            <span className={styles.pinkSpan}> Fortnite</span>
          </h2>
        </div>
      </main>
    </>
  );
};

export default Home;
